# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    #Ldap Parameters
    host: "beaufort.winthrop.edu" #beaufort is student server for testing, use rahway for faculty
    port: 636
    version: 3
    useSsl: true #this enables ldaps VERY IMPORTANT THAT THIS IS TRUE!!!
    useTls: false
    optRef: false

    search_dn: "cn=visitor,cn=Users,dc=acc,dc=winthrop,dc=edu" #for beaufort
    search_password: "winthrop"
    base_dn: "cn=Users,dc=acc,dc=winthrop,dc=edu" #for beaufort
    search_query: "(sAMAccountName={username})"
    default_roles: ['ROLE_USER']
    uid_key: "sAMAccountName"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.ldap:
        class: Symfony\Component\Ldap\LdapClient
        arguments: ["%host%", "%port%", "%version%", "%useSsl%", "%useTls%", "%optRef%"]

#    app.login_listener:
#        class: AppBundle\EventListener\LoginListener
#        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app.session_ldap_provider:
        class: AppBundle\Security\LdapSessionUserProvider
        arguments: ['@app.ldap', '@doctrine.orm.entity_manager', '%base_dn%', '%search_dn%', '%search_password%', '%default_roles%', '%uid_key%'] #use default filter for LdapUserProvider
